### ISSUE TITLE
Documents list not being sorted by publishedAt data

### ISSUE THREAD

**Issue by avitorio** [avitorio/outstatic#231]
Based on this [discussion](https://github.com/avitorio/outstatic/discussions/230).

Lists are not currently being sorted by date.

**Comment by joaoalberto-dev** [comment]
@avitorio looks like this issue was fixed [here](https://github.com/avitorio/outstatic/pull/235). Do you mind closing it?

**Comment by avitorio** [comment]
@joaoalberto-dev ah yes, thanks for the reminder!

**Comment by h34lthbybr33** [comment]
Just want to call out, while the fix works on the client it doesn't remediate a core issue on the server. Because this field (`publishedAt`) is typed as a string, sorting becomes wonky when you try to filter through `db.find({ ... })`.

Assuming:

```
type BlogPost = OstDocument & { ... };
```

I would expect the following to work:

```
const posts = await db.find<({ collection: 'posts', publishedAt: { $lte: Date.now().toString() } })
```

Because it's a string, the filter really can't do much other than a string comparison (which inverts the logic now to use `$gte` vs `$lte`).

I came across this while trying to "future publish" (set date for future, not caring about sensitivity of the post, just that it didn't bubble up to UX "formally" until the date had passed).
